server:
  port: 8989

spring:
  main:
    allow-circular-references: true
  application:
    name: devops
  datasource:
    url: jdbc:postgresql://localhost:5432/devops
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
